### ISSUE TITLE
Can't seem to add any component.

### ISSUE THREAD

**Issue by Joe23232** [sdfgeoff/blender_bevy_toolkit#10]
Hey man so I can't seem to add any component to an object,

![image](https://user-images.githubusercontent.com/34926497/132697812-00e25474-d15f-4183-b4d5-4ec8a0a3b01e.png)

Not too sure why this is happening mate?

**Comment by sdfgeoff** [comment]
In order to add a component you need to tell the exporter what components are available in your game.

The editor looks for files in a 'component_defintions' folder in the same directory as your blend file. Eg:
![structure](https://user-images.githubusercontent.com/13490050/132930654-e1e4ab09-9c9c-4bfb-b216-1f1c695d8184.jpg)

You can see some examples for these files in the `core_definitions` and `rapier_definitions` folders, or look at the ones below:

Simple "tag" struct
```json
{
    "name": "GncComputer",
    "description": "Coordinates RCS thrusters and main engines to produce a desired motion",
    "id": "space_ship_gnc_computer",
    "struct": "game::ship_parts::gnc_computer::GncComputer",
    "fields": []
}
```

Simple parameter:
```json
{
    "name": "Engine",
    "description": "Used to apply thrust to an object",
    "id": "space_ship_engine",
    "struct": "game::ship_parts::engine::Engine",
    "fields": [
        {
            "field": "max_thrust_newtons", 
            "type": "f64", 
            "default": 10.0,
            "description": "The max amount of force the engine can apply, measured in Newtons"
        }
    ]
}
```


Actually, I remember this didn't work on windows a couple months back. One of my friends fixed it, let me push the changes.

**Comment by Joe23232** [comment]
@sdfgeoff 

![image](https://user-images.githubusercontent.com/34926497/132932051-ec26c961-d5e8-4eb7-b8b8-0e77fdc663cb.png)

So in regards to this image, so if I had all of these files, then suddenly if I go to "add component" in Blender, then I will see all the components such as `clock.json`, `com_node.json` etc?

So how does the `json` files work, what would I put inside the `json` files? Or does it get auto generated?

> Actually, I remember this didn't work on windows a couple months back. One of my friends fixed it, let me push the changes.

So when you push the changes, do I have to reinstall the Blender extension?

**Comment by sdfgeoff** [comment]
@Joe23232 I've just pushed the changes. Yes you will have to re-install the addon.

What you put inside the JSON files depends on what components you have in your game.

Eg from the example above:
```json
{
    "name": "Engine",
    "description": "Used to apply thrust to an object",
    "id": "space_ship_engine",
    "struct": "game::ship_parts::engine::Engine",
    "fields": [
        {
            "field": "max_thrust_newtons", 
            "type": "f64", 
            "default": 10.0,
            "description": "The max amount of force the engine can apply, measured in Newtons"
        }
    ]
}
```

- "name" => What appears in blender
- "description" => Text that appears when you over over it in blender
- "id" => Should be unique for this component. (Used to store data internally to the blend file between saves)
- "struct" => This is a path to the struct that represents your object in bevy. Finding this can be a bit hard as it doesn't follow through `pub use` statements, it has to be the path to the module where the struct is actually defined.
- "fields" => These are what properties the component has. For example, in rust, the engine looks like:
```rust
/// An engine applies thrust to the spacecraft
use bevy::prelude::*;

#[derive(Reflect, Default)]
#[reflect(Component)]
pub struct Engine {
    /// The amount of force the engine can apply, measured in Newtons
    pub max_thrust_newtons: f64,

    #[reflect(ignore)]
    pub current_thrust_newtons: f64,
}
```
See also: https://crates.io/crates/bevy_reflect

Each field has the following parameters:
 - "field" => the name. Needs to match with the rust struct field
 - "type" => what type it is. Currently supported are "string", "bool", "f64", "f32", "int", "vec3", "vec2" and "u8enum"
 - "default" => what value to use when the user hasn't set one yet. Note that for type "u8enum" this is instead an array of options for the user to pick from. 
 - "description" => help text for the user.

**Comment by Joe23232** [comment]
@sdfgeoff Hey man.

So I uninstalled the all addon and I installed the new addon.

> What you put inside the JSON files depends on what components you have in your game.
Eg from the example above:

So I added this exact same script:

```
{
    "name": "Engine",
    "description": "Used to apply thrust to an object",
    "id": "space_ship_engine",
    "struct": "game::ship_parts::engine::Engine",
    "fields": [
        {
            "field": "max_thrust_newtons", 
            "type": "f64", 
            "default": 10.0,
            "description": "The max amount of force the engine can apply, measured in Newtons"
        }
    ]
}
```

into a file called `windmill.json` inside the folder `component_definitions`. In the outside directory of `component_definitions` I have a file called `Demo.blend`. And I still can't see any components to add.

![image](https://user-images.githubusercontent.com/34926497/132936242-47b276ed-babf-4d1b-a87d-4beb1922e791.png)

not too sure why this is happening?

**Comment by Joe23232** [comment]
Starting a new thread at https://github.com/sdfgeoff/blender_bevy_toolkit/issues/11 @sdfgeoff
